openapi: 3.1.0
info:
  title: sample
  version: "1.0"
servers:
  - url: "http://localhost"
paths:
  "/api/sample/{id}":
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
      operationId: get-api-sample
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  /api/posts/{post_id}:
    parameters:
      - schema:
          type: number
        name: postId
        in: path
        required: true
    get:
      summary: ""
      operationId: post-get-sample
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./SampleComponent.yaml"
  /api/sample:
    post:
      summary: ""
      operationId: post-api-sample
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./SampleComponent.yaml"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
              required:
                - id
components:
  schemas:
    Sample:
      title: sample
      type: object
      properties:
        id:
          type: number
        status:
          type: string
      required:
        - id
        - status
