openapi: 3.0.0
x-stoplight:
  id: bulvwt9bl88m1
info:
  title: sample
  version: '1.0'
  contact: {}
  description: Stoplight Studio によって作成した、Sample API です
servers:
  - url: 'http://localhost:3080'
    description: スタブサーバ
  - description: ローカル環境API
    url: 'http://localhost'
paths:
  '/api/posts/{postId}':
    parameters:
      - schema:
          type: number
        name: postId
        in: path
        required: true
    get:
      description: 'description'
      summary: ''
      operationId: post-get-sample
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./SampleComponent.yaml
      tags:
        - Posts
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
    Post:
      $ref: ./Post.yaml
  securitySchemes:
    session:
      name: サーバーサイドセッション
      type: apiKey
      in: cookie
tags:
  - name: Posts
  - name: Users
